spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET_KEY}
bank:
  account:
    bin: ES003199
  card:
    bin: 777700
transfer-network:
  base-url: http://transfer-network-api:8078
  endpoint: /api/v1/transfers
payment-network:
  base-url: http://payment-network-api:8079
  endpoint: /api/v1/card-payments/authorizations